/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package QuizProgram;

import java.awt.CardLayout;
import java.awt.Color;
import java.util.Iterator;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;

/**
 *
 * @author GGPC
 */
public class MainFrame extends javax.swing.JFrame {
    public List<Question> questions;
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        textPanel = new javax.swing.JPanel();
        menuTitle = new javax.swing.JLabel();
        buttonsPanel = new javax.swing.JPanel();
        button1 = new javax.swing.JButton();
        button2 = new javax.swing.JButton();
        button3 = new javax.swing.JButton();
        button4 = new javax.swing.JButton();
        difficultyPanel = new javax.swing.JPanel();
        difficultyHeader = new javax.swing.JPanel();
        Question1 = new javax.swing.JLabel();
        difficultyBack = new javax.swing.JButton();
        difficultyOptions = new javax.swing.JPanel();
        button9 = new javax.swing.JButton();
        button10 = new javax.swing.JButton();
        button11 = new javax.swing.JButton();
        gamePanel = new javax.swing.JPanel();
        gameHeaderPanel = new javax.swing.JPanel();
        questionNumber = new javax.swing.JLabel();
        winningsLabel = new javax.swing.JLabel();
        howToBack1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        questionText = new javax.swing.JTextArea();
        skipButton = new javax.swing.JButton();
        fiftyFiftyButton = new javax.swing.JButton();
        answersPanel = new javax.swing.JPanel();
        answer1 = new javax.swing.JButton();
        answer2 = new javax.swing.JButton();
        answer4 = new javax.swing.JButton();
        answer3 = new javax.swing.JButton();
        howToPanel = new javax.swing.JPanel();
        howToHeaderPanel = new javax.swing.JPanel();
        howToPlayTitle = new javax.swing.JLabel();
        howToBack = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        leaderboardPanel = new javax.swing.JPanel();
        leaderboardHeaderPanel = new javax.swing.JPanel();
        leaderboardTitle = new javax.swing.JLabel();
        leaderboardBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Who Wants To Be A Millionaire");
        setBackground(new java.awt.Color(255, 204, 255));
        setPreferredSize(new java.awt.Dimension(970, 690));
        setResizable(false);

        mainPanel.setBackground(new java.awt.Color(255, 204, 255));
        mainPanel.setName(""); // NOI18N
        mainPanel.setPreferredSize(new java.awt.Dimension(970, 690));
        mainPanel.setLayout(new java.awt.CardLayout());

        menuPanel.setBackground(new java.awt.Color(255, 204, 255));
        menuPanel.setPreferredSize(new java.awt.Dimension(970, 690));
        menuPanel.setLayout(new java.awt.BorderLayout());

        textPanel.setOpaque(false);

        menuTitle.setFont(new java.awt.Font("Century Schoolbook", 1, 32)); // NOI18N
        menuTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuTitle.setText("Welcome to Who Wants To Be A Millionaire!");
        menuTitle.setAlignmentX(0.5F);

        javax.swing.GroupLayout textPanelLayout = new javax.swing.GroupLayout(textPanel);
        textPanel.setLayout(textPanelLayout);
        textPanelLayout.setHorizontalGroup(
            textPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(textPanelLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(menuTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 860, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        textPanelLayout.setVerticalGroup(
            textPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, textPanelLayout.createSequentialGroup()
                .addContainerGap(148, Short.MAX_VALUE)
                .addComponent(menuTitle)
                .addGap(133, 133, 133))
        );

        menuPanel.add(textPanel, java.awt.BorderLayout.CENTER);

        buttonsPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 30, 30, 30));
        buttonsPanel.setOpaque(false);
        buttonsPanel.setLayout(new java.awt.GridLayout(2, 2, 30, 10));

        button1.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 24)); // NOI18N
        button1.setText("Start Game");
        button1.setPreferredSize(new java.awt.Dimension(250, 150));
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        buttonsPanel.add(button1);

        button2.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 24)); // NOI18N
        button2.setText("Endless Mode");
        button2.setPreferredSize(new java.awt.Dimension(250, 150));
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        buttonsPanel.add(button2);

        button3.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 24)); // NOI18N
        button3.setText("How to Play");
        button3.setPreferredSize(new java.awt.Dimension(250, 150));
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                howToPlayButtonPressed(evt);
            }
        });
        buttonsPanel.add(button3);

        button4.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 24)); // NOI18N
        button4.setText("Leaderboard");
        button4.setPreferredSize(new java.awt.Dimension(250, 150));
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leaderboardButtonPressed(evt);
            }
        });
        buttonsPanel.add(button4);

        menuPanel.add(buttonsPanel, java.awt.BorderLayout.SOUTH);

        mainPanel.add(menuPanel, "menuPanel");

        difficultyPanel.setBackground(new java.awt.Color(255, 204, 255));
        difficultyPanel.setPreferredSize(new java.awt.Dimension(970, 690));
        difficultyPanel.setLayout(new java.awt.BorderLayout());

        difficultyHeader.setOpaque(false);

        Question1.setFont(new java.awt.Font("Century Schoolbook", 1, 32)); // NOI18N
        Question1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Question1.setText("Please Select a Difficulty");
        Question1.setAlignmentX(0.5F);

        difficultyBack.setBackground(new java.awt.Color(255, 153, 153));
        difficultyBack.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 24)); // NOI18N
        difficultyBack.setText("Back");
        difficultyBack.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        difficultyBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                difficultyBack(evt);
            }
        });

        javax.swing.GroupLayout difficultyHeaderLayout = new javax.swing.GroupLayout(difficultyHeader);
        difficultyHeader.setLayout(difficultyHeaderLayout);
        difficultyHeaderLayout.setHorizontalGroup(
            difficultyHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(difficultyHeaderLayout.createSequentialGroup()
                .addGroup(difficultyHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(difficultyHeaderLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(difficultyBack, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(difficultyHeaderLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(Question1, javax.swing.GroupLayout.PREFERRED_SIZE, 860, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        difficultyHeaderLayout.setVerticalGroup(
            difficultyHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(difficultyHeaderLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(difficultyBack, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(Question1)
                .addContainerGap(162, Short.MAX_VALUE))
        );

        difficultyPanel.add(difficultyHeader, java.awt.BorderLayout.CENTER);

        difficultyOptions.setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 30, 30, 30));
        difficultyOptions.setOpaque(false);
        difficultyOptions.setLayout(new java.awt.GridLayout(2, 2, 30, 10));

        button9.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 24)); // NOI18N
        button9.setText("Easy");
        button9.setPreferredSize(new java.awt.Dimension(250, 150));
        button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button9ActionPerformed(evt);
            }
        });
        difficultyOptions.add(button9);

        button10.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 24)); // NOI18N
        button10.setText("Medium");
        button10.setPreferredSize(new java.awt.Dimension(250, 150));
        button10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button10ActionPerformed(evt);
            }
        });
        difficultyOptions.add(button10);

        button11.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 24)); // NOI18N
        button11.setText("Hard");
        button11.setPreferredSize(new java.awt.Dimension(250, 150));
        button11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button11ActionPerformed(evt);
            }
        });
        difficultyOptions.add(button11);

        difficultyPanel.add(difficultyOptions, java.awt.BorderLayout.SOUTH);

        mainPanel.add(difficultyPanel, "difficultyPanel");

        gamePanel.setBackground(new java.awt.Color(255, 204, 255));
        gamePanel.setPreferredSize(new java.awt.Dimension(970, 690));
        gamePanel.setLayout(new java.awt.BorderLayout());

        gameHeaderPanel.setOpaque(false);

        questionNumber.setFont(new java.awt.Font("Century Schoolbook", 1, 32)); // NOI18N
        questionNumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        questionNumber.setAlignmentX(0.5F);

        winningsLabel.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 16)); // NOI18N
        winningsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        winningsLabel.setAlignmentX(0.5F);

        howToBack1.setBackground(new java.awt.Color(255, 153, 153));
        howToBack1.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 24)); // NOI18N
        howToBack1.setText("Back");
        howToBack1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        howToBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gameBack(evt);
            }
        });

        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane2.setViewportBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(255, 204, 255)));
        jScrollPane2.setOpaque(false);
        jScrollPane2.setWheelScrollingEnabled(false);
        jScrollPane2.setOpaque(false);
        jScrollPane2.getViewport().setOpaque(false);
        jScrollPane2.setBorder(null);

        questionText.setEditable(false);
        questionText.setColumns(20);
        questionText.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        questionText.setRows(5);
        questionText.setBorder(null);
        questionText.setOpaque(false);
        questionText.setOpaque(false);
        questionText.setBackground(new Color(0, 0, 0, 0)); 
        questionText.setLineWrap(true);
        questionText.setWrapStyleWord(true);
        questionText.setBorder(null);
        jScrollPane2.setViewportView(questionText);

        skipButton.setBackground(new java.awt.Color(204, 255, 204));
        skipButton.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 24)); // NOI18N
        skipButton.setText("Skip");
        skipButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        skipButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skipButton(evt);
            }
        });

        fiftyFiftyButton.setBackground(new java.awt.Color(204, 255, 204));
        fiftyFiftyButton.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 24)); // NOI18N
        fiftyFiftyButton.setText("50:50");
        fiftyFiftyButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fiftyFiftyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiftyFiftyButton(evt);
            }
        });

        answersPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 30, 30, 30));
        answersPanel.setOpaque(false);
        answersPanel.setLayout(new java.awt.GridLayout(2, 2, 30, 10));

        answer1.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 16)); // NOI18N
        answer1.setPreferredSize(new java.awt.Dimension(250, 150));
        answer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer1(evt);
            }
        });
        answersPanel.add(answer1);

        answer2.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 16)); // NOI18N
        answer2.setPreferredSize(new java.awt.Dimension(250, 150));
        answer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer2ActionPerformed(evt);
            }
        });
        answersPanel.add(answer2);

        answer4.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 16)); // NOI18N
        answer4.setPreferredSize(new java.awt.Dimension(250, 150));
        answer4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer4leaderboardButtonPressed(evt);
            }
        });
        answersPanel.add(answer4);

        answer3.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 16)); // NOI18N
        answer3.setPreferredSize(new java.awt.Dimension(250, 150));
        answer3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer3howToPlayButtonPressed(evt);
            }
        });
        answersPanel.add(answer3);

        javax.swing.GroupLayout gameHeaderPanelLayout = new javax.swing.GroupLayout(gameHeaderPanel);
        gameHeaderPanel.setLayout(gameHeaderPanelLayout);
        gameHeaderPanelLayout.setHorizontalGroup(
            gameHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gameHeaderPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(howToBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(questionNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101)
                .addComponent(fiftyFiftyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(skipButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(gameHeaderPanelLayout.createSequentialGroup()
                .addGap(282, 282, 282)
                .addComponent(winningsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gameHeaderPanelLayout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(gameHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gameHeaderPanelLayout.createSequentialGroup()
                        .addComponent(answersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 872, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gameHeaderPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 807, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78))))
        );
        gameHeaderPanelLayout.setVerticalGroup(
            gameHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gameHeaderPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(gameHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(questionNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(gameHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(howToBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fiftyFiftyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(skipButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(winningsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(answersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        gamePanel.add(gameHeaderPanel, java.awt.BorderLayout.PAGE_START);

        mainPanel.add(gamePanel, "gamePanel");

        howToPanel.setBackground(new java.awt.Color(255, 204, 255));
        howToPanel.setName(""); // NOI18N
        howToPanel.setPreferredSize(new java.awt.Dimension(970, 690));
        howToPanel.setLayout(new java.awt.BorderLayout());

        howToHeaderPanel.setBackground(new java.awt.Color(255, 204, 255));

        howToPlayTitle.setFont(new java.awt.Font("Century Schoolbook", 1, 36)); // NOI18N
        howToPlayTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        howToPlayTitle.setText("How to Play");
        howToPlayTitle.setAlignmentX(0.5F);

        howToBack.setBackground(new java.awt.Color(255, 153, 153));
        howToBack.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 24)); // NOI18N
        howToBack.setText("Back");
        howToBack.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        howToBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                howToBack(evt);
            }
        });

        javax.swing.GroupLayout howToHeaderPanelLayout = new javax.swing.GroupLayout(howToHeaderPanel);
        howToHeaderPanel.setLayout(howToHeaderPanelLayout);
        howToHeaderPanelLayout.setHorizontalGroup(
            howToHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(howToHeaderPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(howToBack, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(220, 220, 220)
                .addComponent(howToPlayTitle)
                .addContainerGap(374, Short.MAX_VALUE))
        );
        howToHeaderPanelLayout.setVerticalGroup(
            howToHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(howToHeaderPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(howToHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(howToBack, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(howToPlayTitle))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        howToPanel.add(howToHeaderPanel, java.awt.BorderLayout.NORTH);

        jScrollPane3.setBorder(null);
        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane3.setMinimumSize(new java.awt.Dimension(200, 200));
        jScrollPane3.setOpaque(false);

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(255, 204, 255));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 23)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setText("           In this game you will be asked 10 random questions at a difficulty of your choosing! \n                  You will be presented with 4 possible answers but only ONE will be correct.\n\n             You have two lifelines which can each help you out with a question if you're stuck. \n            50:50 will get rid of two incorrect answers (Only works on questions with 4 answers)\n                                                   Skip will skip the current question.\n\n                                 To answer questions, click on the button with your answer.\n                              To activate your lifelines, click on the buttons in the top right.\n\n                   Each question you answer will earn you more money and if you get all 10\n                         correct, you win $1,000,000! Get one wrong and it's back to zero!");
        jTextArea2.setBorder(null);
        jTextArea2.setDisabledTextColor(null);
        jTextArea2.setOpaque(false);
        jScrollPane3.setViewportView(jTextArea2);

        howToPanel.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        mainPanel.add(howToPanel, "howToPanel");

        leaderboardPanel.setBackground(new java.awt.Color(255, 204, 255));
        leaderboardPanel.setName(""); // NOI18N
        leaderboardPanel.setPreferredSize(new java.awt.Dimension(970, 690));
        leaderboardPanel.setLayout(new java.awt.BorderLayout());

        leaderboardHeaderPanel.setBackground(new java.awt.Color(255, 204, 255));

        leaderboardTitle.setFont(new java.awt.Font("Century Schoolbook", 1, 36)); // NOI18N
        leaderboardTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        leaderboardTitle.setText("Leaderboard");
        leaderboardTitle.setAlignmentX(0.5F);

        leaderboardBack.setBackground(new java.awt.Color(255, 153, 153));
        leaderboardBack.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 24)); // NOI18N
        leaderboardBack.setText("Back");
        leaderboardBack.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        leaderboardBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leaderboardBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout leaderboardHeaderPanelLayout = new javax.swing.GroupLayout(leaderboardHeaderPanel);
        leaderboardHeaderPanel.setLayout(leaderboardHeaderPanelLayout);
        leaderboardHeaderPanelLayout.setHorizontalGroup(
            leaderboardHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leaderboardHeaderPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(leaderboardBack, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(211, 211, 211)
                .addComponent(leaderboardTitle)
                .addContainerGap(366, Short.MAX_VALUE))
        );
        leaderboardHeaderPanelLayout.setVerticalGroup(
            leaderboardHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leaderboardHeaderPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(leaderboardHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(leaderboardBack, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(leaderboardTitle))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        leaderboardPanel.add(leaderboardHeaderPanel, java.awt.BorderLayout.NORTH);

        mainPanel.add(leaderboardPanel, "leaderboardPanel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        CardLayout cardLayout = (CardLayout) mainPanel.getLayout();
        cardLayout.show(mainPanel, "difficultyPanel");
    }//GEN-LAST:event_button1ActionPerformed

    private void howToPlayButtonPressed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_howToPlayButtonPressed
        CardLayout cardLayout = (CardLayout) mainPanel.getLayout();
        cardLayout.show(mainPanel, "howToPanel");
    }//GEN-LAST:event_howToPlayButtonPressed

    private void leaderboardButtonPressed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leaderboardButtonPressed
        CardLayout cardLayout = (CardLayout) mainPanel.getLayout();
        cardLayout.show(mainPanel, "leaderboardPanel");
    }//GEN-LAST:event_leaderboardButtonPressed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button2ActionPerformed

    private void howToBack(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_howToBack
        CardLayout cardLayout = (CardLayout) mainPanel.getLayout();
        cardLayout.show(mainPanel, "menuPanel");
    }//GEN-LAST:event_howToBack

    private void answer1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer1
        // TODO add your handling code here:
    }//GEN-LAST:event_answer1

    private void answer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answer2ActionPerformed

    private void answer3howToPlayButtonPressed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer3howToPlayButtonPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_answer3howToPlayButtonPressed

    private void answer4leaderboardButtonPressed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer4leaderboardButtonPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_answer4leaderboardButtonPressed

    private void gameBack(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gameBack
        CardLayout cardLayout = (CardLayout) mainPanel.getLayout();
        cardLayout.show(mainPanel, "menuPanel");
    }//GEN-LAST:event_gameBack

    private void leaderboardBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leaderboardBackActionPerformed
        CardLayout cardLayout = (CardLayout) mainPanel.getLayout();
        cardLayout.show(mainPanel, "menuPanel");
    }//GEN-LAST:event_leaderboardBackActionPerformed

    private void difficultyBack(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_difficultyBack
        CardLayout cardLayout = (CardLayout) mainPanel.getLayout();
        cardLayout.show(mainPanel, "menuPanel");
    }//GEN-LAST:event_difficultyBack

    private void button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button9ActionPerformed
        questions = API.fetchQuestions("easy");
        CardLayout cardLayout = (CardLayout) mainPanel.getLayout();
        cardLayout.show(mainPanel, "gamePanel"); 
        GUIGameplay newGame = new GUIGameplay(questions);
        newGame.askNextQuestion();
    }//GEN-LAST:event_button9ActionPerformed

    private void button10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button10ActionPerformed
        questions = API.fetchQuestions("medium");
        CardLayout cardLayout = (CardLayout) mainPanel.getLayout();
        cardLayout.show(mainPanel, "gamePanel");
        GUIGameplay newGame = new GUIGameplay(questions);
        newGame.askNextQuestion();
    }//GEN-LAST:event_button10ActionPerformed

    private void button11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button11ActionPerformed
        questions = API.fetchQuestions("hard");
        CardLayout cardLayout = (CardLayout) mainPanel.getLayout();
        cardLayout.show(mainPanel, "gamePanel");
        GUIGameplay newGame = new GUIGameplay(questions);
        newGame.askNextQuestion();
    }//GEN-LAST:event_button11ActionPerformed

    private void skipButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skipButton
        skipButton.setBackground(new Color(255, 153, 153));
        GUILifeline.skip(GUIGameplay.getCurrentQuestion(), GUIGameplay.getCurrentOptions());
    }//GEN-LAST:event_skipButton

    private void fiftyFiftyButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiftyFiftyButton
        GUILifeline.fiftyFifty(GUIGameplay.getCurrentOptions(), GUIGameplay.getCurrentCorrectAnswer(), GUIGameplay.getAnswerButtons());
    }//GEN-LAST:event_fiftyFiftyButton

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Question1;
    public static javax.swing.JButton answer1;
    public static javax.swing.JButton answer2;
    public static javax.swing.JButton answer3;
    public static javax.swing.JButton answer4;
    private javax.swing.JPanel answersPanel;
    private javax.swing.JButton button1;
    private javax.swing.JButton button10;
    private javax.swing.JButton button11;
    private javax.swing.JButton button2;
    private javax.swing.JButton button3;
    private javax.swing.JButton button4;
    private javax.swing.JButton button9;
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JButton difficultyBack;
    private javax.swing.JPanel difficultyHeader;
    private javax.swing.JPanel difficultyOptions;
    private javax.swing.JPanel difficultyPanel;
    public static javax.swing.JButton fiftyFiftyButton;
    private javax.swing.JPanel gameHeaderPanel;
    private javax.swing.JPanel gamePanel;
    private javax.swing.JButton howToBack;
    private javax.swing.JButton howToBack1;
    private javax.swing.JPanel howToHeaderPanel;
    private javax.swing.JPanel howToPanel;
    private javax.swing.JLabel howToPlayTitle;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JButton leaderboardBack;
    private javax.swing.JPanel leaderboardHeaderPanel;
    private javax.swing.JPanel leaderboardPanel;
    private javax.swing.JLabel leaderboardTitle;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JLabel menuTitle;
    public static javax.swing.JLabel questionNumber;
    public static javax.swing.JTextArea questionText;
    public static javax.swing.JButton skipButton;
    private javax.swing.JPanel textPanel;
    public static javax.swing.JLabel winningsLabel;
    // End of variables declaration//GEN-END:variables
}
